version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    ports:
      - "4000:80"

  backend:
    build: ./backend
    ports:
      - "4001:4001"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
