version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "4000:4000"
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "4001:4001"
    restart: unless-stopped

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    volumes:
      - /etc/letsencrypt/live/supergym.tony219y.com:/etc/nginx/certs:ro
    restart: unless-stopped
