services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    ports:
      - "4000:80"

  backend:
    build: ./backend
    ports:
      - "4001:4001"
