name: Deploy to super-gym

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to VPS via SSH
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.VPS_IP }} "
            cd /var/www/super-gym &&
            git pull origin main &&
            docker-compose down &&
            docker-compose up -d --build
          "